apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    app: voting-app
spec:
  containers:
    - image:  redis
      name: redis
      ports:
        - containerPort: 80