apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: voting-app
spec:
  containers:
    - image:  dockersamples/examplevotingapp_worker
      name: worker-app